### ISSUE TITLE
Segfault while using Discord

### ISSUE THREAD

**Issue by fzwoch** [AyatanaIndicators/libayatana-appindicator-glib#64]
This looks similar to #54.

It has been working fine since the above fix for quite some some. Within the last couple weeks I have seen crashes again:

```
[42330.038887] Discord[3879]: segfault at 1e6cf2e04000 ip 00007fc109231715 sp 00007fffc0033e50 error 4 in libayatana-appindicator3.so.1.0.0[7fc10922d000+6000] likely on CPU 2 (core 2, socket 0)
[42330.038894] Code: 48 85 ed 0f 84 8c 00 00 00 48 8d 54 24 0c 48 8d 74 24 10 4c 89 f7 31 db e8 38 bc ff ff 0f 1f 84 00 00 00 00 00 48 8b 44 24 10 <48> 8b 3c d8 39 5c 24 0c 7f 09 48 85 ff 0f 85 98 01 00 00 48 89 ee
[47477.021257] Discord[74382]: segfault at 2db1e603b000 ip 00007f168a271715 sp 00007ffccb727460 error 4 in libayatana-appindicator3.so.1.0.0[7f168a26d000+6000] likely on CPU 5 (core 5, socket 0)
[47477.021272] Code: 48 85 ed 0f 84 8c 00 00 00 48 8d 54 24 0c 48 8d 74 24 10 4c 89 f7 31 db e8 38 bc ff ff 0f 1f 84 00 00 00 00 00 48 8b 44 24 10 <48> 8b 3c d8 39 5c 24 0c 7f 09 48 85 ff 0f 85 98 01 00 00 48 89 ee
[52572.930582] Discord[83204]: segfault at 3dc85fd08000 ip 00007fa87de21715 sp 00007fff3cbce180 error 4 in libayatana-appindicator3.so.1.0.0[7fa87de1d000+6000] likely on CPU 8 (core 0, socket 0)
[52572.930597] Code: 48 85 ed 0f 84 8c 00 00 00 48 8d 54 24 0c 48 8d 74 24 10 4c 89 f7 31 db e8 38 bc ff ff 0f 1f 84 00 00 00 00 00 48 8b 44 24 10 <48> 8b 3c d8 39 5c 24 0c 7f 09 48 85 ff 0f 85 98 01 00 00 48 89 ee
[55343.535063] Discord[87445]: segfault at 183ca6c97000 ip 00007f26cd33b715 sp 00007fff9e71f320 error 4 in libayatana-appindicator3.so.1.0.0[7f26cd337000+6000] likely on CPU 4 (core 4, socket 0)
[55343.535083] Code: 48 85 ed 0f 84 8c 00 00 00 48 8d 54 24 0c 48 8d 74 24 10 4c 89 f7 31 db e8 38 bc ff ff 0f 1f 84 00 00 00 00 00 48 8b 44 24 10 <48> 8b 3c d8 39 5c 24 0c 7f 09 48 85 ff 0f 85 98 01 00 00 48 89 ee
[57929.786876] Discord[92792]: segfault at 3355ac722000 ip 00007f8122e59715 sp 00007ffdf444b420 error 4 in libayatana-appindicator3.so.1.0.0[7f8122e55000+6000] likely on CPU 6 (core 6, socket 0)
[57929.786885] Code: 48 85 ed 0f 84 8c 00 00 00 48 8d 54 24 0c 48 8d 74 24 10 4c 89 f7 31 db e8 38 bc ff ff 0f 1f 84 00 00 00 00 00 48 8b 44 24 10 <48> 8b 3c d8 39 5c 24 0c 7f 09 48 85 ff 0f 85 98 01 00 00 48 89 ee
```

Not sure if it is the same issue, or another one. Could be a Discord update that does something differently now?

However the time span it starting happening again seems to be in line with the release of `0.5.92` and when the update got pushed to Debian unstable.

Unfortunately I don't have any stack traces as of yet.

**Comment by fzwoch** [comment]
```
#0  0x00007fffeb859715 in  () at /lib/x86_64-linux-gnu/libappindicator3.so.1
#1  0x00007ffff7f503b0 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff7f63076 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff7f69bf5 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff7f69dbf in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007fffeb8584e7 in app_indicator_set_icon_full () at /lib/x86_64-linux-gnu/libappindicator3.so.1
```
At least a stack trace, although no symbols.

**Comment by fzwoch** [comment]
```
Thread 1 "Discord" received signal SIGSEGV, Segmentation fault.
0x00007fffeb058715 in status_icon_changes (self=0x237751a2f2f0, data=<optimized out>) at ./src/app-indicator.c:1623
1623	./src/app-indicator.c: No such file or directory.
(gdb) bt
#0  0x00007fffeb058715 in status_icon_changes (self=0x237751a2f2f0, data=<optimized out>) at ./src/app-indicator.c:1623
#1  0x00007ffff7f503b0 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff7f63076 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff7f69bf5 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff7f69dbf in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007fffeb0574e7 in app_indicator_set_icon_full
    (self=0x237751a2f2f0, icon_name=0x2377528f90d1 "discord1_4085", icon_desc=0x5555562f83bb "icon") at ./src/app-indicator.c:2021
#6  0x00005555574aeebd in  ()
#7  0x0000000000000000 in  ()

(gdb) info locals
path = 0x2377532e6000
n_elements = 4096
i = 840704
found = 0
icon = 0x237751ec3c30
priv = <optimized out>
icon_theme = 0x237751cabe40
theme_path = <optimized out>
icon_name = <optimized out>
```

**Comment by fzwoch** [comment]
There has been a Discord update 3 weeks ago. I haven't had a crash since. So I guess it was Discord at fault..
